import type { Metadata } from "next";
import { site, SITE_URL, SOCIALS } from "@/lib/config";

/**
 * SEO helpers. The AI-edited "train.py" side of the AutoResearch SEO loop — scored by
 * execution/autoresearch/score/score_seo.py. All URLs derive from SITE_URL (config-driven)
 * and are resolved to absolute by `metadataBase` (set in app/layout.tsx).
 *
 * Bilingual note: the site serves one URL per page (German by default; language toggles
 * client-side via cookie). We therefore advertise availability in both languages with
 * og:locale (de_DE) + og:locale:alternate (en_US) rather than per-language hreflang URLs.
 */

export const DEFAULT_OG_LOCALE = "de_DE";
export const ALTERNATE_OG_LOCALE = "en_US";

/**
 * The site-wide OG image, generated by app/opengraph-image.tsx. Next does NOT carry the
 * file-based image onto routes that export their own `openGraph` object, so we reference
 * it explicitly here to guarantee og:image on every page. metadataBase makes it absolute.
 */
export const OG_IMAGE = "/opengraph-image";

type PageMetaInput = {
  /** Full, ready-to-render <title> (aim for ~30–60 chars, unique per route). */
  title: string;
  /** Meta description (aim for ~120–160 chars, unique per route). */
  description: string;
  /** Route path beginning with "/", e.g. "/produkte". Used for canonical + og:url. */
  path: string;
};

/**
 * Build a complete per-page Metadata object. Next.js does NOT deep-merge `openGraph`
 * across layouts, so each page must emit a full set — this returns one. The og:image is
 * supplied site-wide by app/opengraph-image.tsx (inherited), so we deliberately omit
 * `openGraph.images` here to let that file-based image apply.
 */
export function buildMetadata({ title, description, path }: PageMetaInput): Metadata {
  const url = path === "/" ? "/" : path.replace(/\/+$/, "");
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: site.company,
      locale: DEFAULT_OG_LOCALE,
      alternateLocale: ALTERNATE_OG_LOCALE,
      type: "website",
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [OG_IMAGE],
    },
  };
}

/**
 * JSON-LD Organization for the site (rendered once in the root layout, inherited by all
 * pages for the scorer's `jsonld_present` check and for rich results in search).
 */
export function organizationJsonLd(): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: site.company,
    url: SITE_URL,
    logo: `${SITE_URL}/opengraph-image`,
    description: site.tagline,
    email: site.contact_email,
    sameAs: SOCIALS.map((s) => s.href),
  };
}
