#!/usr/bin/env python3
"""Regenerate sites/<slug>/.env.local from root .env + site.config.json.

Run this before `next dev` in any site directory. It is also safe to re-run after
editing .env or site.config.json — it always rewrites .env.local from the two sources
of truth so local dev never drifts from what gets deployed.

Which shared vars get written depends on what the site actually has:

  has_contact_form  -> Supabase (server-side) + LEAD_COLUMNS + Gmail
  has_blog          -> Supabase (server-side) + the two NEXT_PUBLIC_SUPABASE_* vars

Both features talk to the same Supabase project, so SUPABASE_URL/SUPABASE_SERVICE_KEY
are written when either is enabled. A site with neither gets only its identity vars.

The NEXT_PUBLIC_* pair is separate from the server-side pair on purpose: the blog admin
signs authors in with the ANON key through @supabase/ssr, so that key has to reach the
browser, and NEXT_PUBLIC_ is what inlines it at build time. It is public by design
(RLS is what protects the data). SUPABASE_SERVICE_KEY must never be given that prefix.

Usage:
    python execution/sync_env_local.py --slug acme
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    from dotenv import dotenv_values
except ImportError:
    print("python-dotenv not installed. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
SITES = REPO_ROOT / "sites"

# Shared vars (root .env), grouped by the feature that needs them.
# Server-side Supabase: required by both the lead form and the blog.
SUPABASE_ENV_VARS = [
    "SUPABASE_URL",
    "SUPABASE_SERVICE_KEY",
]

# Lead capture + notification mail.
FORM_ENV_VARS = [
    "LEAD_COLUMNS",
    "GMAIL_USER",
    "GMAIL_APP_PASSWORD",
]

# Browser-visible Supabase credentials for the blog admin's auth session.
# Public by design; never put SUPABASE_SERVICE_KEY behind a NEXT_PUBLIC_ prefix.
BLOG_ENV_VARS = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
]

# Per-site vars sourced from site.config.json. CONTACT_EMAIL is only written when
# the site has a contact form.
CONFIG_TO_ENV = {
    "slug": "SITE_SLUG",
    "company": "COMPANY_NAME",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--slug", required=True)
    args = parser.parse_args()

    site_dir = SITES / args.slug
    config_path = site_dir / "site.config.json"
    if not config_path.is_file():
        print(f"missing {config_path}", file=sys.stderr)
        return 2

    # A hand-edited site.config.json with a trailing comma would otherwise dump a raw
    # traceback, which reads like a bug in this script rather than a typo in the file.
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"invalid JSON in {config_path}: {exc}", file=sys.stderr)
        return 2

    missing_cfg = [k for k in CONFIG_TO_ENV if not config.get(k)]
    if missing_cfg:
        print(f"site.config.json missing required fields: {missing_cfg}", file=sys.stderr)
        return 2

    has_form = bool(config.get("has_contact_form"))
    # Absent means false: existing site.config.json files predate the blog feature and
    # must keep generating exactly the .env.local they generated before.
    has_blog = bool(config.get("has_blog"))

    lines = [
        "# Auto-generated by execution/sync_env_local.py — do not hand-edit.",
        "# Source of truth: ../../.env (shared) + site.config.json (per-site).",
        "",
        "# --- per-site (from site.config.json) ---",
    ]
    for cfg_key, env_key in CONFIG_TO_ENV.items():
        lines.append(f"{env_key}={config[cfg_key]}")

    if has_form:
        contact_email = str(config.get("contact_email", "")).strip()
        if not contact_email or "@" not in contact_email:
            print(
                f"site.config.json `contact_email` looks invalid: {contact_email!r}\n"
                f"  → set it to the operator inbox before running this script.\n"
                f"  → file: {config_path}",
                file=sys.stderr,
            )
            return 2
        lines.append(f"CONTACT_EMAIL={contact_email}")

    # Build the shared list from the enabled features. Order is fixed and duplicate-free
    # so re-running never reshuffles .env.local and shows a spurious diff.
    shared_vars: list[str] = []
    if has_form or has_blog:
        shared_vars += SUPABASE_ENV_VARS
    if has_form:
        shared_vars += FORM_ENV_VARS
    if has_blog:
        shared_vars += BLOG_ENV_VARS

    if shared_vars:
        root_env_path = REPO_ROOT / ".env"
        if not root_env_path.is_file():
            print(f"missing {root_env_path}", file=sys.stderr)
            return 2
        root_env = dotenv_values(root_env_path)
        missing_env = [k for k in shared_vars if not root_env.get(k)]
        if missing_env:
            print(f"root .env missing required vars: {missing_env}", file=sys.stderr)
            return 2

        lines += ["", "# --- shared (from ../../.env) ---"]
        for env_key in shared_vars:
            lines.append(f"{env_key}={root_env[env_key]}")

    env_local_path = site_dir / ".env.local"
    env_local_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {env_local_path}")
    print(f"  SITE_SLUG        = {config['slug']}")
    print(f"  COMPANY_NAME     = {config['company']}")
    if has_form:
        print(f"  CONTACT_EMAIL    = {config['contact_email']}")
    # Names only, never values — this output can end up in a log or a screen share.
    if shared_vars:
        print(f"  + {len(shared_vars)} shared var(s) from root .env: {', '.join(shared_vars)}")
    else:
        print("  (no contact form and no blog — no shared vars written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
