#!/usr/bin/env python3
"""Regenerate sites/<slug>/.env.local from root .env + site.config.json.

Run this before `next dev` in any site directory. It is also safe to re-run
after editing .env or site.config.json — it always rewrites .env.local from
the two sources of truth so local dev never drifts from what gets deployed.

Usage:
    python execution/sync_env_local.py --slug agentic-workflows-101
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

try:
    from dotenv import dotenv_values
except ImportError:
    print("python-dotenv not installed. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
SITES = REPO_ROOT / "sites"

SHARED_ENV_VARS = [
    "SUPABASE_URL",
    "SUPABASE_SERVICE_KEY",
    "LEAD_COLUMNS",
    "GMAIL_USER",
    "GMAIL_APP_PASSWORD",
]

CONFIG_TO_ENV = {
    "slug": "CAMPAIGN_SLUG",
    "drive_link": "DRIVE_LINK",
    "lead_magnet_title": "LEAD_MAGNET_TITLE",
    "company": "COMPANY_NAME",
}

PLACEHOLDER_MARKERS = ("<id>", "<slug>", "your-", "example.com", "FILL_IN")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--slug", required=True)
    args = parser.parse_args()

    site_dir = SITES / args.slug
    config_path = site_dir / "site.config.json"
    if not config_path.is_file():
        print(f"missing {config_path}", file=sys.stderr)
        return 2

    config = json.loads(config_path.read_text(encoding="utf-8"))

    missing_cfg = [k for k in CONFIG_TO_ENV if not config.get(k)]
    if missing_cfg:
        print(f"site.config.json missing required fields: {missing_cfg}", file=sys.stderr)
        return 2

    drive_link = str(config.get("drive_link", ""))
    if not drive_link.startswith("http") or any(m in drive_link for m in PLACEHOLDER_MARKERS):
        print(
            f"site.config.json `drive_link` looks like a placeholder: {drive_link!r}\n"
            f"  → set it to the actual Google Drive folder URL before running this script.\n"
            f"  → file: {config_path}",
            file=sys.stderr,
        )
        return 2

    root_env_path = REPO_ROOT / ".env"
    if not root_env_path.is_file():
        print(f"missing {root_env_path}", file=sys.stderr)
        return 2

    root_env = dotenv_values(root_env_path)
    missing_env = [k for k in SHARED_ENV_VARS if not root_env.get(k)]
    if missing_env:
        print(f"root .env missing required vars: {missing_env}", file=sys.stderr)
        return 2

    lines = [
        "# Auto-generated by execution/sync_env_local.py — do not hand-edit.",
        "# Source of truth: ../../.env (shared) + site.config.json (per-campaign).",
        "",
        "# --- per-campaign (from site.config.json) ---",
    ]
    for cfg_key, env_key in CONFIG_TO_ENV.items():
        lines.append(f"{env_key}={config[cfg_key]}")

    lines += ["", "# --- shared (from ../../.env) ---"]
    for env_key in SHARED_ENV_VARS:
        lines.append(f"{env_key}={root_env[env_key]}")

    env_local_path = site_dir / ".env.local"
    env_local_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {env_local_path}")
    print(f"  CAMPAIGN_SLUG     = {config['slug']}")
    print(f"  LEAD_MAGNET_TITLE = {config['lead_magnet_title']}")
    print(f"  DRIVE_LINK        = {drive_link}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
